### PR TITLE
Bundle parser for Apollo

### PR DESCRIPTION
**Pull request by abhiaiyer91**
- [x] Need to export printer

### CODE REVIEW

**Comment by stubailo** [comment]
I don't think we need to uglify right?

**Comment by stubailo** [comment]
Also do you think the dependencies of the printer and parser overlap? Do you think it's possible to make one bundle that includes both? We could make an entry point file that imports the two modules and run webpack once, I think that would deduplicate any deps

**Comment by abhiaiyer91** [comment]
Yeah we dont need to uglify! I will look into overlapping deps!

**Comment by abhiaiyer91** [comment]
No overlapping deps!

**Comment by stubailo** [comment]
This looks great!

**Pull request merged**
