### PR TITLE
Enforce consistent indentation style

### PR DESCRIPTION
**Pull request by gajus**
https://github.com/apollostack/graphql-tag/pull/9 introduced tabs. I have noticed only post merge. This PR fixes the style issue introduced by the #9 and adds .editorconfig to prevent future mistakes such as this one.

### CODE REVIEW

**Comment by stubailo** [comment]
Hmm, we probably want to set up linting then. I just published a new version, perhaps you can rebase this PR?

**Comment by gajus** [comment]
> Hmm, we probably want to set up linting then. I just published a new version, perhaps you can rebase this PR?

You most certainly should...

Ideally test and lint should be done precommit, e.g. f806b2074b0fdb6a1e4617b21b9d74497adf8b7c.

**Comment by stubailo** [comment]
This package is super small, so it doesn't seem like it needs that much structure. I'd definitely be open to having linting though just to avoid stuff like tabs/spaces.

Having tests run pre-commit sounds pretty rough since that would make intermediate commits more onerous since you need to either skip the hook or make all tests pass.

**Comment by gajus** [comment]
> Having tests run pre-commit sounds pretty rough since that would make intermediate commits more onerous since you need to either skip the hook or make all tests pass.

I had more or less the same argument (https://github.com/gajus/react-css-modules/pull/174) with @lbeschastny. I was wrong.

Having a precommit hook for test/lint most definitely saves time and makes commit history cleaner.

**Comment by gajus** [comment]
> I'd definitely be open to having linting though just to avoid stuff like tabs/spaces.

Just use https://github.com/airbnb/babel-preset-airbnb.

Or if you prefer biased and strict rules, https://github.com/gajus/eslint-config-canonical.

**Comment by stubailo** [comment]
I'm open to either - usually I use airbnb with one or two custom rules but I'm not super opinionated as long as it's consistent.

**Comment by stubailo** [comment]
Thanks for the spacing fix! I don't think we need to ship a new version, but it's much better now.

**Pull request merged**
